/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import BL.Mail;
import java.io.InputStream;
import javax.mail.internet.MimeBodyPart;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Pablo MB
 */
public class FrNuevoMail extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrNuevoMail
     */
    public FrNuevoMail() {
        initComponents();
        btnCC.enable(false);
        txtAsunto.enable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNMPrincipal = new javax.swing.JPanel();
        btnPara = new javax.swing.JButton();
        txtPara = new javax.swing.JTextField();
        btnCC = new javax.swing.JButton();
        txtAsunto = new javax.swing.JTextField();
        chCC = new javax.swing.JCheckBox();
        btnAdjuntar = new javax.swing.JButton();
        txtArchivo = new javax.swing.JTextField();
        chAdjuntar = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCuerpo = new javax.swing.JTextArea();
        btnEnviar = new javax.swing.JButton();
        lblAsunto = new javax.swing.JLabel();
        txtCC = new javax.swing.JTextField();
        btnGuardarBorradores = new javax.swing.JButton();

        btnPara.setText("Para...");

        btnCC.setText("CC...");

        chCC.setText("Agregar CC?");

        btnAdjuntar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/paperclip4_black.png"))); // NOI18N
        btnAdjuntar.setText("Adjuntar archivo...");

        chAdjuntar.setText("Adjuntar archivo?");

        txtCuerpo.setColumns(20);
        txtCuerpo.setRows(5);
        jScrollPane1.setViewportView(txtCuerpo);

        btnEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/send.png"))); // NOI18N
        btnEnviar.setText("Enviar!");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        lblAsunto.setText("Asunto:");

        btnGuardarBorradores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/save_all.png"))); // NOI18N
        btnGuardarBorradores.setText("Guardar en borradores");
        btnGuardarBorradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarBorradoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNMPrincipalLayout = new javax.swing.GroupLayout(panelNMPrincipal);
        panelNMPrincipal.setLayout(panelNMPrincipalLayout);
        panelNMPrincipalLayout.setHorizontalGroup(
            panelNMPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNMPrincipalLayout.createSequentialGroup()
                .addGroup(panelNMPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNMPrincipalLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnPara)
                        .addGap(6, 6, 6)
                        .addComponent(txtPara, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelNMPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelNMPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCC, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAsunto, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelNMPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelNMPrincipalLayout.createSequentialGroup()
                                .addComponent(txtCC, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chCC))))
                    .addGroup(panelNMPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAdjuntar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chAdjuntar))
                    .addGroup(panelNMPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelNMPrincipalLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelNMPrincipalLayout.createSequentialGroup()
                            .addGap(262, 262, 262)
                            .addComponent(btnGuardarBorradores)
                            .addGap(18, 18, 18)
                            .addComponent(btnEnviar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelNMPrincipalLayout.setVerticalGroup(
            panelNMPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNMPrincipalLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panelNMPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPara, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPara, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panelNMPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsunto)
                    .addComponent(txtAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNMPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chCC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNMPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdjuntar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtArchivo)
                    .addComponent(chAdjuntar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNMPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarBorradores, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelNMPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelNMPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        Mail nuevoCorreo = new Mail();
        if(chCC.isSelected()){
            btnCC.enable(true);
            txtCC.enable(true);
            
            nuevoCorreo.setCc(txtCC.getText());
        }
        if(chAdjuntar.isSelected()){
            btnAdjuntar.enable(true);
            txtArchivo.enable(true);
            
            
        }
        nuevoCorreo.setAsunto(txtAsunto.getText());
        nuevoCorreo.setCuerpo(txtCuerpo.getText());
        nuevoCorreo.setPara(txtPara.getText());
        
        if(nuevoCorreo.enviar())
            JOptionPane.showMessageDialog(null, "Mensaje enviado!","Alerta!", JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(null, "Error al enviar el mensaje,intente de nuevo","Error!",JOptionPane.ERROR);
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnGuardarBorradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarBorradoresActionPerformed
        
    }//GEN-LAST:event_btnGuardarBorradoresActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdjuntar;
    private javax.swing.JButton btnCC;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnGuardarBorradores;
    private javax.swing.JButton btnPara;
    private javax.swing.JCheckBox chAdjuntar;
    private javax.swing.JCheckBox chCC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAsunto;
    private javax.swing.JPanel panelNMPrincipal;
    private javax.swing.JTextField txtArchivo;
    private javax.swing.JTextField txtAsunto;
    private javax.swing.JTextField txtCC;
    private javax.swing.JTextArea txtCuerpo;
    private javax.swing.JTextField txtPara;
    // End of variables declaration//GEN-END:variables
}
