/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author Jose Pablo MB
 */
public class FrPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrPrincipal
     */        
    
    public FrPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        lpPrincipal = new javax.swing.JLayeredPane();
        btnNuevoCorreo = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        nuevoCorreo = new javax.swing.JMenuItem();
        nuevaBandeja = new javax.swing.JMenuItem();
        separador = new javax.swing.JPopupMenu.Separator();
        listaContactos = new javax.swing.JMenuItem();
        edit = new javax.swing.JMenu();
        mantenimiento = new javax.swing.JMenuItem();
        acerca = new javax.swing.JMenu();
        acercaD = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1190, 700));
        setPreferredSize(new java.awt.Dimension(1190, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lpPrincipal.setMinimumSize(new java.awt.Dimension(1190, 700));
        getContentPane().add(lpPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, 1990, 700));

        btnNuevoCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/window_new.png"))); // NOI18N
        btnNuevoCorreo.setText("Nuevo correo...");
        btnNuevoCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 40));

        file.setText("File");

        nuevoCorreo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        nuevoCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/window_new.png"))); // NOI18N
        nuevoCorreo.setText("Nuevo correo...");
        nuevoCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoCorreoActionPerformed(evt);
            }
        });
        file.add(nuevoCorreo);

        nuevaBandeja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/folder_new.png"))); // NOI18N
        nuevaBandeja.setText("Registrar correo");
        nuevaBandeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaBandejaActionPerformed(evt);
            }
        });
        file.add(nuevaBandeja);
        file.add(separador);

        listaContactos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        listaContactos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/preferences_contact_list.png"))); // NOI18N
        listaContactos.setText("Contactos");
        listaContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaContactosActionPerformed(evt);
            }
        });
        file.add(listaContactos);

        menuBar.add(file);

        edit.setText("Edit");

        mantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/maintenance_time.png"))); // NOI18N
        mantenimiento.setText("Mantenimiento...");
        edit.add(mantenimiento);

        menuBar.add(edit);

        acerca.setText("Acerca de...");

        acercaD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/info.png"))); // NOI18N
        acercaD.setText("Acerca de esta aplicación");
        acerca.add(acercaD);

        menuBar.add(acerca);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoCorreoActionPerformed
        FrNuevoMail nuevoMail = new FrNuevoMail();
        lpPrincipal.add(nuevoMail);
        nuevoMail.setVisible(true);
    }//GEN-LAST:event_btnNuevoCorreoActionPerformed

    private void nuevoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoCorreoActionPerformed
        FrNuevoMail nuevoMail = new FrNuevoMail();
        lpPrincipal.add(nuevoMail);
        nuevoMail.setVisible(true);
    }//GEN-LAST:event_nuevoCorreoActionPerformed

    private void nuevaBandejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaBandejaActionPerformed
        FrRegistrarCorreo frc = new FrRegistrarCorreo();
        lpPrincipal.add(frc);
        frc.setVisible(true);
    }//GEN-LAST:event_nuevaBandejaActionPerformed

    private void listaContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaContactosActionPerformed
        FrNuevoContacto fnc = new FrNuevoContacto();
        lpPrincipal.add(fnc);
        fnc.setVisible(true);
    }//GEN-LAST:event_listaContactosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu acerca;
    private javax.swing.JMenuItem acercaD;
    private javax.swing.JButton btnNuevoCorreo;
    private javax.swing.JMenu edit;
    private javax.swing.JMenu file;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem listaContactos;
    private javax.swing.JLayeredPane lpPrincipal;
    private javax.swing.JMenuItem mantenimiento;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem nuevaBandeja;
    private javax.swing.JMenuItem nuevoCorreo;
    private javax.swing.JPopupMenu.Separator separador;
    // End of variables declaration//GEN-END:variables
}
