/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author Jose Pablo MB
 */
public class FrRegistrarCorreo extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrRegistrarCorreo
     */
    public FrRegistrarCorreo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRCPrincipal = new javax.swing.JPanel();
        lblDirCorreo = new javax.swing.JLabel();
        lblContra = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtContra = new javax.swing.JPasswordField();
        lblArroba = new javax.swing.JLabel();
        lblApodo = new javax.swing.JLabel();
        txtApodo = new javax.swing.JTextField();
        cbCliente = new javax.swing.JComboBox();
        btnComprobar = new javax.swing.JButton();
        chPorDefecto = new javax.swing.JCheckBox();

        setToolTipText("Agregue un nuevo correo");

        panelRCPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar nuevo correo electrónico"));
        panelRCPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblDirCorreo.setText("Dirección de correo:");

        lblContra.setText("Contraseña:");

        lblArroba.setText("@");

        lblApodo.setText("Apodo:");

        cbCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "gmail.com", "hotmail.com" }));

        btnComprobar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/symbol_check.png"))); // NOI18N
        btnComprobar.setText("Comprobar!");

        chPorDefecto.setText("Hacer mi correo por defecto");

        javax.swing.GroupLayout panelRCPrincipalLayout = new javax.swing.GroupLayout(panelRCPrincipal);
        panelRCPrincipal.setLayout(panelRCPrincipalLayout);
        panelRCPrincipalLayout.setHorizontalGroup(
            panelRCPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRCPrincipalLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelRCPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRCPrincipalLayout.createSequentialGroup()
                        .addComponent(chPorDefecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnComprobar))
                    .addGroup(panelRCPrincipalLayout.createSequentialGroup()
                        .addGroup(panelRCPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelRCPrincipalLayout.createSequentialGroup()
                                .addComponent(lblApodo)
                                .addGap(10, 10, 10)
                                .addComponent(txtApodo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRCPrincipalLayout.createSequentialGroup()
                                .addComponent(lblContra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContra))
                            .addGroup(panelRCPrincipalLayout.createSequentialGroup()
                                .addComponent(lblDirCorreo)
                                .addGap(10, 10, 10)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblArroba)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelRCPrincipalLayout.setVerticalGroup(
            panelRCPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRCPrincipalLayout.createSequentialGroup()
                .addGroup(panelRCPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRCPrincipalLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblDirCorreo))
                    .addGroup(panelRCPrincipalLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(panelRCPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblArroba)
                            .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19)
                .addGroup(panelRCPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRCPrincipalLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblContra))
                    .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(panelRCPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRCPrincipalLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblApodo))
                    .addComponent(txtApodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRCPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnComprobar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chPorDefecto))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRCPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRCPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprobar;
    private javax.swing.JComboBox cbCliente;
    private javax.swing.JCheckBox chPorDefecto;
    private javax.swing.JLabel lblApodo;
    private javax.swing.JLabel lblArroba;
    private javax.swing.JLabel lblContra;
    private javax.swing.JLabel lblDirCorreo;
    private javax.swing.JPanel panelRCPrincipal;
    private javax.swing.JTextField txtApodo;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
